{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "otel-demo.fullname" . }}-default
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "otel-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
{{- end }}
