apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.fullname" . }}-paymentservice
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: paymentservice
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-paymentservice
spec:
  type: {{ .Values.payment.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.payment.service.port | default 8080 }}
      targetPort: {{ .Values.payment.service.targetPort | default 8080 }}
      name: tcp-service
  selector:
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-paymentservice