apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.fullname" . }}-valkey
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: valkey
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-valkey
spec:
  type: {{ .Values.valkey.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.valkey.service.port | default 6379 }}
      targetPort: {{ .Values.valkey.service.targetPort | default 6379 }}
      name: valkey
  selector:
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-valkey